CREATE TABLE users (
  id uuid PRIMARY KEY,
  email text NOT NULL,
  phone_number text NOT NULL,
  username text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  address_line_1 text,
  address_line_2 text,
  city text,
  state_region text,
  postal_code text,
  country_code text NOT NULL,
  preferred_locale text NOT NULL,
  email_verified_at timestamptz,
  phone_verified_at timestamptz,
  login_confirmation_method text,
  login_confirmation_enabled_at timestamptz,
  age_verified_at timestamptz,
  is_active boolean NOT NULL,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
