import type { Locale } from './i18n';

export type CyberMindCopy = {
  eyebrow1: string; headline1: string; body1: string;
  callouts: readonly { title: string; body: string }[];
  eyebrow2: string; headline2: string; body2: string;
};

const en: CyberMindCopy = {
  eyebrow1: 'Onboard intelligence',
  headline1: 'The system does not simply respond.\nIt continuously thinks.',
  body1: 'CyberMind is the onboard intelligence inside UNO. Sensors\ncollect information from the system, onboard processing\ncoordinates its operation, and software updates keep the\nplatform evolving. Core functions remain available directly\non UNO—with or without a phone.',
  callouts: [
    { title: '16+ SYSTEM INPUTS', body: 'Heat · water · temperature\nSystem state' },
    { title: 'HIGH-SPEED PROCESSING', body: 'Fast onboard coordination\nacross every active system.' },
    { title: 'HEAT · LIGHT · SOUND', body: 'One core coordinates\nthe complete session.' },
    { title: 'APP DATA EXCHANGE', body: 'Continuous interaction\nwith the RAMSIDER app.' },
    { title: 'ONLINE EVOLUTION', body: 'Supported updates can deliver\nnew functions and control logic.' },
  ],
  eyebrow2: 'SYSTEM INTELLIGENCE', headline2: 'ONE CORE.\nEVERY SYSTEM CONNECTED.',
  body2: 'CyberMind receives data from 16+ system inputs, monitoring\nwater presence, temperature and system state in real time.\nIt coordinates heating, light and sound, exchanges data with\nthe RAMSIDER app and evolves through supported updates.',
};

export const cyberMindCopy: Record<Locale, CyberMindCopy> = {
  en,
  ru: { eyebrow1: 'Встроенный интеллект', headline1: 'Система не просто реагирует.\nОна непрерывно анализирует.', body1: 'CyberMind — встроенный интеллект UNO. Датчики собирают данные о системе, встроенный процессор координирует её работу, а обновления ПО развивают платформу. Основные функции доступны прямо на UNO — с телефоном и без него.', callouts: [{title:'16+ СИСТЕМНЫХ ВХОДОВ',body:'Нагрев · вода · температура\nСостояние системы'},{title:'БЫСТРАЯ ОБРАБОТКА',body:'Оперативная координация\nвсех активных систем.'},{title:'НАГРЕВ · СВЕТ · ЗВУК',body:'Одно ядро управляет\nвсем сеансом.'},{title:'ОБМЕН ДАННЫМИ С ПРИЛОЖЕНИЕМ',body:'Постоянная связь\nс приложением RAMSIDER.'},{title:'РАЗВИТИЕ ОНЛАЙН',body:'Обновления могут добавлять\nфункции и логику управления.'}], eyebrow2:'СИСТЕМНЫЙ ИНТЕЛЛЕКТ',headline2:'ОДНО ЯДРО.\nВСЕ СИСТЕМЫ СВЯЗАНЫ.',body2:'CyberMind получает данные от 16+ системных входов и отслеживает наличие воды, температуру и состояние системы в реальном времени. Он координирует нагрев, свет и звук, обменивается данными с приложением RAMSIDER и развивается благодаря поддерживаемым обновлениям.' },
  de: { eyebrow1:'Intelligenz an Bord',headline1:'Das System reagiert nicht nur.\nEs denkt ständig mit.',body1:'CyberMind ist die integrierte Intelligenz in UNO. Sensoren erfassen Systemdaten, die Verarbeitung an Bord koordiniert den Betrieb und Softwareupdates entwickeln die Plattform weiter. Die Kernfunktionen bleiben direkt am UNO verfügbar – mit oder ohne Smartphone.',callouts:[{title:'16+ SYSTEMEINGÄNGE',body:'Hitze · Wasser · Temperatur\nSystemstatus'},{title:'SCHNELLE VERARBEITUNG',body:'Schnelle Koordination\naller aktiven Systeme.'},{title:'HITZE · LICHT · TON',body:'Ein Kern koordiniert\ndie gesamte Sitzung.'},{title:'DATENAUSTAUSCH MIT APP',body:'Ständige Interaktion\nmit der RAMSIDER App.'},{title:'ONLINE-WEITERENTWICKLUNG',body:'Updates können neue Funktionen\nund Steuerlogik bringen.'}],eyebrow2:'SYSTEMINTELLIGENZ',headline2:'EIN KERN.\nALLE SYSTEME VERBUNDEN.',body2:'CyberMind empfängt Daten von über 16 Systemeingängen und überwacht Wasser, Temperatur und Systemstatus in Echtzeit. Es koordiniert Hitze, Licht und Ton, tauscht Daten mit der RAMSIDER App aus und entwickelt sich durch unterstützte Updates weiter.' },
  fr: { eyebrow1:'Intelligence embarquée',headline1:'Le système ne se contente pas de réagir.\nIl réfléchit en continu.',body1:'CyberMind est l’intelligence embarquée de UNO. Les capteurs recueillent les données du système, le traitement intégré coordonne son fonctionnement et les mises à jour font évoluer la plateforme. Les fonctions essentielles restent accessibles sur UNO, avec ou sans téléphone.',callouts:[{title:'16+ ENTRÉES SYSTÈME',body:'Chaleur · eau · température\nÉtat du système'},{title:'TRAITEMENT RAPIDE',body:'Coordination rapide\nde tous les systèmes actifs.'},{title:'CHALEUR · LUMIÈRE · SON',body:'Un cœur coordonne\ntoute la session.'},{title:'ÉCHANGE AVEC L’APPLICATION',body:'Interaction continue\navec l’application RAMSIDER.'},{title:'ÉVOLUTION EN LIGNE',body:'Les mises à jour peuvent apporter\nde nouvelles fonctions.'}],eyebrow2:'INTELLIGENCE SYSTÈME',headline2:'UN CŒUR.\nTOUS LES SYSTÈMES CONNECTÉS.',body2:'CyberMind reçoit les données de plus de 16 entrées système et surveille l’eau, la température et l’état du système en temps réel. Il coordonne chaleur, lumière et son, échange avec l’application RAMSIDER et évolue grâce aux mises à jour prises en charge.' },
  es: { eyebrow1:'Inteligencia integrada',headline1:'El sistema no solo responde.\nPiensa continuamente.',body1:'CyberMind es la inteligencia integrada de UNO. Los sensores recogen datos del sistema, el procesamiento interno coordina su funcionamiento y las actualizaciones de software hacen evolucionar la plataforma. Las funciones principales siguen disponibles en UNO, con o sin teléfono.',callouts:[{title:'16+ ENTRADAS DEL SISTEMA',body:'Calor · agua · temperatura\nEstado del sistema'},{title:'PROCESAMIENTO RÁPIDO',body:'Coordinación rápida\nde todos los sistemas activos.'},{title:'CALOR · LUZ · SONIDO',body:'Un núcleo coordina\ntoda la sesión.'},{title:'INTERCAMBIO CON LA APP',body:'Interacción continua\ncon la app RAMSIDER.'},{title:'EVOLUCIÓN EN LÍNEA',body:'Las actualizaciones pueden añadir\nfunciones y lógica de control.'}],eyebrow2:'INTELIGENCIA DEL SISTEMA',headline2:'UN NÚCLEO.\nTODOS LOS SISTEMAS CONECTADOS.',body2:'CyberMind recibe datos de más de 16 entradas y supervisa el agua, la temperatura y el estado del sistema en tiempo real. Coordina calor, luz y sonido, intercambia datos con la app RAMSIDER y evoluciona mediante actualizaciones compatibles.' },
  it: { eyebrow1:'Intelligenza integrata',headline1:'Il sistema non si limita a reagire.\nPensa continuamente.',body1:'CyberMind è l’intelligenza integrata di UNO. I sensori raccolgono dati, l’elaborazione interna coordina il funzionamento e gli aggiornamenti software fanno evolvere la piattaforma. Le funzioni principali restano disponibili su UNO, con o senza telefono.',callouts:[{title:'16+ INGRESSI DI SISTEMA',body:'Calore · acqua · temperatura\nStato del sistema'},{title:'ELABORAZIONE RAPIDA',body:'Coordinamento veloce\ndi tutti i sistemi attivi.'},{title:'CALORE · LUCE · SUONO',body:'Un nucleo coordina\nl’intera sessione.'},{title:'SCAMBIO DATI CON L’APP',body:'Interazione continua\ncon l’app RAMSIDER.'},{title:'EVOLUZIONE ONLINE',body:'Gli aggiornamenti possono offrire\nnuove funzioni e controlli.'}],eyebrow2:'INTELLIGENZA DI SISTEMA',headline2:'UN NUCLEO.\nTUTTI I SISTEMI CONNESSI.',body2:'CyberMind riceve dati da oltre 16 ingressi di sistema e monitora acqua, temperatura e stato in tempo reale. Coordina calore, luce e suono, scambia dati con l’app RAMSIDER e si evolve grazie agli aggiornamenti supportati.' },
  tr: { eyebrow1:'Yerleşik zekâ',headline1:'Sistem yalnızca tepki vermez.\nSürekli düşünür.',body1:'CyberMind, UNO içindeki yerleşik zekâdır. Sensörler sistemden veri toplar, yerleşik işlemci çalışmasını koordine eder ve yazılım güncellemeleri platformu geliştirir. Temel işlevler telefonla veya telefonsuz doğrudan UNO’da kullanılabilir.',callouts:[{title:'16+ SİSTEM GİRİŞİ',body:'Isı · su · sıcaklık\nSistem durumu'},{title:'YÜKSEK HIZLI İŞLEME',body:'Tüm etkin sistemlerde\nhızlı koordinasyon.'},{title:'ISI · IŞIK · SES',body:'Tek çekirdek tüm oturumu\nkoordine eder.'},{title:'UYGULAMA VERİ ALIŞVERİŞİ',body:'RAMSIDER uygulamasıyla\nsürekli etkileşim.'},{title:'ÇEVRİMİÇİ GELİŞİM',body:'Güncellemeler yeni işlevler\nve kontrol mantığı sağlayabilir.'}],eyebrow2:'SİSTEM ZEKÂSI',headline2:'TEK ÇEKİRDEK.\nTÜM SİSTEMLER BAĞLI.',body2:'CyberMind, 16’dan fazla sistem girişinden veri alarak su varlığını, sıcaklığı ve sistem durumunu gerçek zamanlı izler. Isı, ışık ve sesi koordine eder, RAMSIDER uygulamasıyla veri alışverişi yapar ve desteklenen güncellemelerle gelişir.' },
  ar: { eyebrow1:'ذكاء مدمج',headline1:'لا يكتفي النظام بالاستجابة.\nبل يفكر باستمرار.',body1:'CyberMind هو الذكاء المدمج داخل UNO. تجمع المستشعرات معلومات النظام، وتنسق المعالجة المدمجة عمله، وتساعد تحديثات البرامج على تطوير المنصة. تظل الوظائف الأساسية متاحة مباشرة على UNO، مع الهاتف أو بدونه.',callouts:[{title:'أكثر من 16 مدخلاً للنظام',body:'الحرارة · الماء · درجة الحرارة\nحالة النظام'},{title:'معالجة عالية السرعة',body:'تنسيق سريع بين جميع\nالأنظمة النشطة.'},{title:'الحرارة · الضوء · الصوت',body:'نواة واحدة تنسق\nالجلسة بالكامل.'},{title:'تبادل بيانات التطبيق',body:'تفاعل مستمر مع\nتطبيق RAMSIDER.'},{title:'تطور عبر الإنترنت',body:'قد توفر التحديثات وظائف\nجديدة ومنطق تحكم جديد.'}],eyebrow2:'ذكاء النظام',headline2:'نواة واحدة.\nكل الأنظمة متصلة.',body2:'يتلقى CyberMind بيانات من أكثر من 16 مدخلاً ويراقب وجود الماء ودرجة الحرارة وحالة النظام لحظياً. ينسق الحرارة والضوء والصوت، ويتبادل البيانات مع تطبيق RAMSIDER ويتطور عبر التحديثات المدعومة.' },
  zh: { eyebrow1:'机载智能',headline1:'系统不只是响应。\n它持续思考。',body1:'CyberMind 是 UNO 内置的智能核心。传感器采集系统信息，机载处理协调运行，软件更新让平台持续发展。核心功能可直接在 UNO 上使用，无论是否连接手机。',callouts:[{title:'16+ 系统输入',body:'热量 · 水 · 温度\n系统状态'},{title:'高速处理',body:'快速协调所有\n运行中的系统。'},{title:'热量 · 灯光 · 声音',body:'一个核心协调\n整个使用过程。'},{title:'应用数据交换',body:'与 RAMSIDER 应用\n持续交互。'},{title:'在线演进',body:'更新可带来新功能\n和控制逻辑。'}],eyebrow2:'系统智能',headline2:'一个核心。\n连接每个系统。',body2:'CyberMind 接收来自 16 个以上系统输入的数据，实时监测水、温度和系统状态。它协调加热、灯光和声音，与 RAMSIDER 应用交换数据，并通过受支持的更新不断发展。' },
  ja: { eyebrow1:'内蔵インテリジェンス',headline1:'システムは反応するだけではない。\n常に考え続ける。',body1:'CyberMind は UNO に内蔵された知能です。センサーが情報を集め、内蔵処理が動作を調整し、ソフトウェア更新がプラットフォームを進化させます。主な機能はスマートフォンの有無にかかわらず UNO から直接利用できます。',callouts:[{title:'16以上のシステム入力',body:'熱 · 水 · 温度\nシステム状態'},{title:'高速処理',body:'稼働中の全システムを\nすばやく連携。'},{title:'熱 · 光 · 音',body:'一つのコアが\nセッション全体を調整。'},{title:'アプリとのデータ交換',body:'RAMSIDER アプリと\n継続的に連携。'},{title:'オンライン進化',body:'更新によって新機能と\n制御ロジックを追加可能。'}],eyebrow2:'システムインテリジェンス',headline2:'一つのコア。\nすべてのシステムを接続。',body2:'CyberMind は16以上のシステム入力からデータを受け取り、水、温度、状態をリアルタイムで監視します。熱、光、音を調整し、RAMSIDER アプリとデータを交換して、対応する更新を通じて進化します。' },
  ko: { eyebrow1:'내장 지능',headline1:'시스템은 반응만 하지 않습니다.\n끊임없이 생각합니다.',body1:'CyberMind는 UNO에 내장된 지능입니다. 센서가 시스템 정보를 수집하고, 내부 처리 기능이 작동을 조율하며, 소프트웨어 업데이트가 플랫폼을 발전시킵니다. 핵심 기능은 휴대전화 유무에 관계없이 UNO에서 바로 사용할 수 있습니다.',callouts:[{title:'16개 이상의 시스템 입력',body:'열 · 물 · 온도\n시스템 상태'},{title:'고속 처리',body:'작동 중인 모든 시스템을\n빠르게 조율합니다.'},{title:'열 · 빛 · 소리',body:'하나의 코어가\n전체 세션을 조율합니다.'},{title:'앱 데이터 교환',body:'RAMSIDER 앱과\n지속적으로 상호 작용.'},{title:'온라인 발전',body:'업데이트로 새 기능과\n제어 로직을 제공할 수 있습니다.'}],eyebrow2:'시스템 인텔리전스',headline2:'하나의 코어.\n모든 시스템 연결.',body2:'CyberMind는 16개 이상의 입력에서 데이터를 받아 물, 온도, 시스템 상태를 실시간으로 확인합니다. 열, 빛, 소리를 조율하고 RAMSIDER 앱과 데이터를 교환하며 지원되는 업데이트를 통해 발전합니다.' },
};
