import type {Locale} from './i18n';
type NobleCopy = readonly [string,string,string,string,string,string];
export const nobleCraftCopy:Record<Locale,NobleCopy>={
 en:['Functional luxury surfaces','LUXURY IS NOT APPLIED.\nIT IS ENGINEERED INTO\nEVERY SURFACE.','NobleCraft brings functional materials into direct contact with the ritual. Titanium, 24K gold PVD and carbon are selected for the role each surface performs—uniting tactile precision, durability and a distinctly RAMSIDER expression.','MATERIAL ARCHITECTURE','PRECISION YOU CAN SEE.\nQUALITY YOU CAN FEEL.','NobleCraft brings together genuine 24K gold PVD, titanium, carbon and precision-finished surfaces across UNO’s functional architecture. Each material is selected for its role—balancing lasting strength, tactile refinement and consistent performance.'],
 ru:['Функциональные премиальные поверхности','РОСКОШЬ НЕ НАНОСИТСЯ.\nОНА ЗАЛОЖЕНА\nВ КАЖДУЮ ПОВЕРХНОСТЬ.','NobleCraft соединяет функциональные материалы с ритуалом. Титан, PVD-покрытие золотом 24K и карбон выбираются по назначению каждой поверхности, объединяя тактильную точность, долговечность и характер RAMSIDER.','АРХИТЕКТУРА МАТЕРИАЛОВ','ТОЧНОСТЬ, КОТОРУЮ ВИДНО.\nКАЧЕСТВО, КОТОРОЕ ЧУВСТВУЕТСЯ.','NobleCraft объединяет настоящее PVD-покрытие золотом 24K, титан, карбон и точно обработанные поверхности в функциональной архитектуре UNO. Каждый материал выбран для своей роли: прочность, тактильная выразительность и стабильная работа.'],
 de:['Funktionale Luxusoberflächen','LUXUS WIRD NICHT AUFGETRAGEN.\nER IST IN JEDE\nOBERFLÄCHE EINGEARBEITET.','NobleCraft verbindet funktionale Materialien direkt mit dem Ritual. Titan, 24K-Gold-PVD und Carbon werden für die Aufgabe jeder Oberfläche gewählt: taktile Präzision, Haltbarkeit und der Ausdruck von RAMSIDER.','MATERIALARCHITEKTUR','PRÄZISION, DIE MAN SIEHT.\nQUALITÄT, DIE MAN FÜHLT.','NobleCraft vereint echtes 24K-Gold-PVD, Titan, Carbon und präzise veredelte Oberflächen in der funktionalen Architektur von UNO. Jedes Material dient seiner Aufgabe und verbindet dauerhafte Festigkeit, taktile Feinheit und konstante Leistung.'],
 fr:['Surfaces de luxe fonctionnelles','LE LUXE NE S’APPLIQUE PAS.\nIL EST CONÇU DANS\nCHAQUE SURFACE.','NobleCraft met les matériaux fonctionnels au contact du rituel. Titane, PVD or 24K et carbone sont choisis pour le rôle de chaque surface, alliant précision tactile, durabilité et expression RAMSIDER.','ARCHITECTURE DES MATÉRIAUX','UNE PRÉCISION VISIBLE.\nUNE QUALITÉ SENSIBLE.','NobleCraft associe véritable PVD or 24K, titane, carbone et surfaces finies avec précision dans l’architecture fonctionnelle d’UNO. Chaque matériau est choisi pour son rôle : résistance durable, finesse tactile et performance constante.'],
 es:['Superficies de lujo funcional','EL LUJO NO SE APLICA.\nSE DISEÑA EN\nCADA SUPERFICIE.','NobleCraft pone materiales funcionales en contacto con el ritual. Titanio, PVD de oro de 24K y carbono se eligen para cada superficie: precisión táctil, durabilidad y expresión RAMSIDER.','ARQUITECTURA DE MATERIALES','PRECISIÓN QUE PUEDES VER.\nCALIDAD QUE PUEDES SENTIR.','NobleCraft reúne PVD de oro auténtico de 24K, titanio, carbono y superficies acabadas con precisión en la arquitectura funcional de UNO. Cada material se elige para su función: resistencia, refinamiento táctil y rendimiento constante.'],
 it:['Superfici di lusso funzionale','IL LUSSO NON SI APPLICA.\nÈ PROGETTATO IN\nOGNI SUPERFICIE.','NobleCraft mette i materiali funzionali a contatto con il rituale. Titanio, PVD in oro 24K e carbonio sono scelti per ogni superficie: precisione tattile, durata ed espressione RAMSIDER.','ARCHITETTURA DEI MATERIALI','PRECISIONE CHE SI VEDE.\nQUALITÀ CHE SI SENTE.','NobleCraft unisce autentico PVD in oro 24K, titanio, carbonio e superfici rifinite con precisione nell’architettura funzionale di UNO. Ogni materiale è scelto per il suo ruolo: resistenza duratura, finezza tattile e prestazioni costanti.'],
 tr:['İşlevsel lüks yüzeyler','LÜKS SONRADAN EKLENMEZ.\nHER YÜZEYİN İÇİNE\nİŞLENİR.','NobleCraft işlevsel malzemeleri ritüelle buluşturur. Titanyum, 24K altın PVD ve karbon her yüzeyin görevi için seçilir: dokunsal hassasiyet, dayanıklılık ve RAMSIDER ifadesi.','MALZEME MİMARİSİ','GÖREBİLDİĞİNİZ HASSASİYET.\nHİSSEDEBİLDİĞİNİZ KALİTE.','NobleCraft gerçek 24K altın PVD, titanyum, karbon ve hassas işlenmiş yüzeyleri UNO’nun işlevsel mimarisinde birleştirir. Her malzeme görevine göre seçilir: kalıcı sağlamlık, dokunsal incelik ve tutarlı performans.'],
 ar:['أسطح فاخرة وعملية','الفخامة ليست طبقة تُضاف.\nإنها هندسة في\nكل سطح.','تجمع NobleCraft المواد العملية مع الطقس مباشرة. يُختار التيتانيوم وطلاء الذهب PVD عيار 24 والكربون لدور كل سطح، لتجتمع الدقة الملموسة والمتانة وطابع RAMSIDER.','هندسة المواد','دقة تراها.\nجودة تشعر بها.','تجمع NobleCraft طلاء الذهب الحقيقي PVD عيار 24 والتيتانيوم والكربون والأسطح المصقولة بدقة في هندسة UNO العملية. تُختار كل مادة لدورها، فتوازن القوة الدائمة والملمس الراقي والأداء الثابت.'],
 zh:['功能性奢华表面','奢华并非表面装饰。\n它融入\n每一处表面。','NobleCraft 让功能材料直接融入仪式。钛、24K 金 PVD 和碳纤维根据各表面的用途选择，融合精准触感、耐用性和独特的 RAMSIDER 表达。','材料架构','看得见的精度。\n感受得到的品质。','NobleCraft 将真正的 24K 金 PVD、钛、碳纤维及精密加工表面融入 UNO 的功能架构。每种材料都为其用途选择，平衡持久强度、细腻触感与稳定性能。'],
 ja:['機能的な高級仕上げ','ラグジュアリーは塗るものではない。\nすべての表面に\n設計されています。','NobleCraft は機能素材をリチュアルに直接結びつけます。チタン、24K 金 PVD、カーボンを各表面の役割に応じて選び、触覚の精密さ、耐久性、RAMSIDER らしさを融合します。','素材のアーキテクチャ','見える精密さ。\n感じる品質。','NobleCraft は本物の24K 金 PVD、チタン、カーボン、精密仕上げの表面を UNO の機能構造に統合します。各素材は役割に応じて選ばれ、持続的な強度、洗練された触感、安定した性能を両立します。'],
 ko:['기능적인 럭셔리 표면','럭셔리는 덧입히는 것이 아닙니다.\n모든 표면 안에\n설계됩니다.','NobleCraft는 기능 소재를 리추얼과 직접 연결합니다. 티타늄, 24K 골드 PVD와 카본을 각 표면의 역할에 맞게 선택해 촉각적 정밀함, 내구성과 RAMSIDER의 표현을 결합합니다.','소재 아키텍처','눈에 보이는 정밀함.\n느낄 수 있는 품질.','NobleCraft는 진정한 24K 골드 PVD, 티타늄, 카본과 정밀 마감 표면을 UNO의 기능 구조에 결합합니다. 모든 소재는 역할에 맞게 선택되어 지속적인 강도, 세련된 촉감과 일관된 성능을 균형 있게 제공합니다.'],
};
export const nobleMaterials:Record<Locale,readonly string[]>={en:['24K GOLD PVD','TITANIUM','CARBON','PRECISION FINISH','MATERIAL QUALITY'],ru:['ЗОЛОТО 24K PVD','ТИТАН','КАРБОН','ТОЧНАЯ ОБРАБОТКА','КАЧЕСТВО МАТЕРИАЛА'],de:['24K-GOLD-PVD','TITAN','CARBON','PRÄZISES FINISH','MATERIALQUALITÄT'],fr:['OR 24K PVD','TITANE','CARBONE','FINITION PRÉCISE','QUALITÉ DES MATÉRIAUX'],es:['ORO 24K PVD','TITANIO','CARBONO','ACABADO PRECISO','CALIDAD MATERIAL'],it:['ORO 24K PVD','TITANIO','CARBONIO','FINITURA PRECISA','QUALITÀ DEI MATERIALI'],tr:['24K ALTIN PVD','TİTANYUM','KARBON','HASSAS İŞLEME','MALZEME KALİTESİ'],ar:['ذهب 24 PVD','تيتانيوم','كربون','تشطيب دقيق','جودة المواد'],zh:['24K金PVD','钛','碳纤维','精密加工','材料品质'],ja:['24K金PVD','チタン','カーボン','精密仕上げ','素材品質'],ko:['24K 골드 PVD','티타늄','카본','정밀 마감','소재 품질']};
export const nobleMaterialDetails:Record<Locale,readonly string[]>={
 en:['Genuine gold coating on GOLD components.','Selected functional elements.','Selected accessories.','Engineered for fit and durability.','Chosen for purpose and performance.'],
 ru:['Настоящее золотое покрытие компонентов GOLD.','Выбранные функциональные элементы.','Выбранные аксессуары.','Точность посадки и долговечность.','Выбрано по назначению и эффективности.'],
 de:['Echte Goldbeschichtung auf GOLD-Komponenten.','Ausgewählte Funktionselemente.','Ausgewähltes Zubehör.','Für Passform und Haltbarkeit.','Für Zweck und Leistung gewählt.'],
 fr:['Véritable or sur les composants GOLD.','Éléments fonctionnels sélectionnés.','Accessoires sélectionnés.','Précision et durabilité.','Choisi pour sa fonction et sa performance.'],
 es:['Oro auténtico en componentes GOLD.','Elementos funcionales seleccionados.','Accesorios seleccionados.','Precisión y durabilidad.','Elegido por función y rendimiento.'],
 it:['Oro autentico sui componenti GOLD.','Elementi funzionali selezionati.','Accessori selezionati.','Precisione e durata.','Scelto per funzione e prestazioni.'],
 tr:['GOLD bileşenlerinde gerçek altın kaplama.','Seçili işlevsel parçalar.','Seçili aksesuarlar.','Uyum ve dayanıklılık için.','Amaç ve performans için seçildi.'],
 ar:['طلاء ذهب حقيقي على أجزاء GOLD.','عناصر عملية مختارة.','ملحقات مختارة.','دقة ومتانة.','مختار للغرض والأداء.'],
 zh:['GOLD部件的真正镀金。','精选功能部件。','精选配件。','精确配合与耐用性。','为用途和性能选择。'],
 ja:['GOLD部品に本物の金コーティング。','厳選された機能部品。','厳選されたアクセサリー。','精密な適合と耐久性。','用途と性能で選定。'],
 ko:['GOLD 부품의 진정한 금 코팅.','선별된 기능 부품.','선별된 액세서리.','정밀한 맞춤과 내구성.','용도와 성능에 맞게 선택.']};

const selectedQuality:Record<Locale,string>={en:"SELECTED QUALITY",ru:"ОТБОРНОЕ КАЧЕСТВО",de:"AUSGEWÄHLTE QUALITÄT",fr:"QUALITÉ SÉLECTIONNÉE",es:"CALIDAD SELECCIONADA",it:"QUALITÀ SELEZIONATA",tr:"SEÇİLMİŞ KALİTE",ar:"جودة مختارة",zh:"精选品质",ja:"厳選された品質",ko:"엄선된 품질"};
export const nobleIconCaptions=(locale:Locale)=>[...nobleMaterials[locale].slice(0,4),selectedQuality[locale]];
