import type { Locale } from './i18n';

export type TechnologySlideId = '02' | '03' | '04' | '05';
export type TechnologyDescriptionCopy = {
  three: string; upper: string; grillMode: string; lower: string;
  upperBody: string; grillBody: string; lowerBody: string; architecture: string; heatersBody: string;
  sails: string; release: string; sailsBody: string;
  profiles: string; power: string; profilesBody: string; create: string; control: string; refine: string;
  surface: string; finishes: string; finishesBody: string;
  heatingCurve: string; grill: string; upperShort: string; lowerShort: string;
};

export const technologyDescriptionCopy: Record<Locale, TechnologyDescriptionCopy> = {
  en: { upperShort: 'UPPER', lowerShort: 'LOWER',
    three: 'THREE HEATERS.\nONE CONTINUOUS BALANCE.', upper: 'UPPER HEAT', grillMode: 'GRILL MODE', lower: 'LOWER HEAT',
    upperBody: 'Maintains the primary\nsession temperature.', grillBody: 'Adds focused\nintensity precisely\nwhen needed.', lowerBody: 'Gradually preheats the\nblend from below.',
    architecture: 'Precision heating architecture', heatersBody: 'Three independently controlled heaters shape and maintain\nthe selected profile, directing heat precisely where it is needed.',
    sails: 'ACTIVE AIR SAILS', release: 'EXCESS HEAT.\nCONTINUOUSLY RELEASED.',
    sailsBody: 'Twin aluminium air sails draw excess heat away from the capsule\nchamber and lower heater. Continuous passive release keeps\nthe blend stable, predictable and protected from overheating\nthroughout the session.',
    profiles: 'PROGRAMMABLE HEAT PROFILES', power: 'POWER, SHAPED OVER TIME.',
    profilesBody: 'HeatCore uses linear and interval algorithms to control how\npower changes throughout the session. Build and refine the\nheating profile in the RAMSIDER app, then manage the active\nsession directly from UNO’s touch display.',
    create: 'CREATE IN APP', control: 'CONTROL ON UNO', refine: 'REFINE THE PROFILE',
    surface: 'PRECISION SURFACE ENGINEERING', finishes: 'GOLD FOR PURITY.\nTITANIUM NITRIDE FOR HEAT.',
    finishesBody: 'HeatCore is offered in two engineered PVD finishes.\nFull-surface 24K gold gives the Gold edition a clean, precise\nexpression of taste and a distinctly noble character.\nTitanium nitride equips the PRO edition for high-temperature\nstability under frequent, sustained use.',
    heatingCurve: 'HEATING CURVE', grill: 'GRILL',
  },
  ru: { upperShort: 'ВЕРХНИЙ', lowerShort: 'НИЖНИЙ',
    three: 'ТРИ НАГРЕВАТЕЛЯ.\nНЕПРЕРЫВНЫЙ БАЛАНС.', upper: 'ВЕРХНИЙ НАГРЕВ', grillMode: 'РЕЖИМ ГРИЛЯ', lower: 'НИЖНИЙ НАГРЕВ',
    upperBody: 'Поддерживает основную температуру сеанса.', grillBody: 'Точно добавляет интенсивность, когда это необходимо.', lowerBody: 'Постепенно прогревает смесь снизу.',
    architecture: 'Архитектура точного нагрева', heatersBody: 'Три независимо управляемых нагревателя формируют и поддерживают выбранный профиль, направляя тепло именно туда, где оно необходимо.',
    sails: 'АКТИВНЫЕ ВОЗДУШНЫЕ ПАРУСА', release: 'ИЗБЫТОЧНОЕ ТЕПЛО.\nНЕПРЕРЫВНЫЙ ОТВОД.', sailsBody: 'Два алюминиевых воздушных паруса отводят избыточное тепло от камеры капсулы и нижнего нагревателя. Непрерывный пассивный отвод сохраняет стабильность и предсказуемость смеси, защищая её от перегрева на протяжении сеанса.',
    profiles: 'ПРОГРАММИРУЕМЫЕ ПРОФИЛИ НАГРЕВА', power: 'МОЩНОСТЬ, ЗАДАННАЯ ВО ВРЕМЕНИ.', profilesBody: 'HeatCore использует линейные и интервальные алгоритмы для управления изменением мощности в течение сеанса. Создавайте и настраивайте профиль нагрева в приложении RAMSIDER, затем управляйте активным сеансом с сенсорного дисплея UNO.',
    create: 'СОЗДАЙТЕ В ПРИЛОЖЕНИИ', control: 'УПРАВЛЯЙТЕ НА UNO', refine: 'НАСТРОЙТЕ ПРОФИЛЬ',
    surface: 'ТОЧНАЯ ИНЖЕНЕРИЯ ПОВЕРХНОСТЕЙ', finishes: 'ЗОЛОТО ДЛЯ ЧИСТОТЫ.\nНИТРИД ТИТАНА ДЛЯ НАГРЕВА.', finishesBody: 'HeatCore предлагается с двумя инженерными PVD-покрытиями. Покрытие всей поверхности золотом 24K придаёт версии Gold чистое, точное выражение вкуса и благородный характер. Нитрид титана обеспечивает версии PRO высокотемпературную стабильность при частом и длительном использовании.',
    heatingCurve: 'КРИВАЯ НАГРЕВА', grill: 'ГРИЛЬ',
  },
  de: { upperShort: 'OBEN', lowerShort: 'UNTEN',
    three: 'DREI HEIZELEMENTE.\nEIN KONTINUIERLICHES GLEICHGEWICHT.', upper: 'OBERE WÄRME', grillMode: 'GRILLMODUS', lower: 'UNTERE WÄRME', upperBody: 'Hält die grundlegende Sitzungstemperatur.', grillBody: 'Erhöht die Intensität gezielt, wenn sie gebraucht wird.', lowerBody: 'Wärmt die Mischung allmählich von unten vor.',
    architecture: 'Präzise Heizarchitektur', heatersBody: 'Drei unabhängig geregelte Heizelemente formen und halten das gewählte Profil und leiten die Wärme genau dorthin, wo sie benötigt wird.',
    sails: 'AKTIVE LUFTSEGEL', release: 'ÜBERSCHÜSSIGE WÄRME.\nKONTINUIERLICH ABGEFÜHRT.', sailsBody: 'Zwei Aluminium-Luftsegel leiten überschüssige Wärme von der Kapselkammer und dem unteren Heizelement ab. Die kontinuierliche passive Abgabe hält die Mischung während der gesamten Sitzung stabil, berechenbar und vor Überhitzung geschützt.',
    profiles: 'PROGRAMMIERBARE WÄRMEPROFILE', power: 'LEISTUNG, ÜBER DIE ZEIT GEFORMT.', profilesBody: 'HeatCore nutzt lineare und Intervallalgorithmen, um Leistungsänderungen während der Sitzung zu steuern. Erstellen und verfeinern Sie das Wärmeprofil in der RAMSIDER App und steuern Sie die aktive Sitzung dann direkt über das Touchdisplay von UNO.', create: 'IN DER APP ERSTELLEN', control: 'AUF UNO STEUERN', refine: 'DAS PROFIL VERFEINERN',
    surface: 'PRÄZISE OBERFLÄCHENTECHNIK', finishes: 'GOLD FÜR REINHEIT.\nTITANNITRID FÜR WÄRME.', finishesBody: 'HeatCore ist mit zwei technisch entwickelten PVD-Oberflächen erhältlich. Vollflächiges 24K-Gold verleiht der Gold Edition einen klaren, präzisen Ausdruck von Geschmack und einen ausgesprochen edlen Charakter. Titannitrid verleiht der PRO Edition Hochtemperaturstabilität bei häufiger, dauerhafter Nutzung.', heatingCurve: 'HEIZKURVE', grill: 'GRILL',
  },
  fr: { upperShort: 'HAUT', lowerShort: 'BAS',
    three: 'TROIS ÉLÉMENTS CHAUFFANTS.\nUN ÉQUILIBRE CONTINU.', upper: 'CHALEUR SUPÉRIEURE', grillMode: 'MODE GRIL', lower: 'CHALEUR INFÉRIEURE', upperBody: 'Maintient la température principale de la session.', grillBody: 'Ajoute une intensité ciblée au moment voulu.', lowerBody: 'Préchauffe progressivement le mélange par le bas.', architecture: 'Architecture de chauffe précise', heatersBody: 'Trois éléments chauffants contrôlés indépendamment définissent et maintiennent le profil choisi, dirigeant la chaleur précisément où elle est nécessaire.',
    sails: 'VOLETS D’AIR ACTIFS', release: 'CHALEUR EXCÉDENTAIRE.\nÉVACUÉE EN CONTINU.', sailsBody: 'Deux volets d’air en aluminium éloignent la chaleur excédentaire de la chambre de capsule et de l’élément chauffant inférieur. L’évacuation passive continue maintient le mélange stable, prévisible et protégé contre la surchauffe pendant toute la session.',
    profiles: 'PROFILS DE CHAUFFE PROGRAMMABLES', power: 'LA PUISSANCE, MODELÉE DANS LE TEMPS.', profilesBody: 'HeatCore utilise des algorithmes linéaires et par intervalles pour contrôler l’évolution de la puissance pendant la session. Créez et affinez le profil de chauffe dans l’application RAMSIDER, puis gérez la session active directement sur l’écran tactile d’UNO.', create: 'CRÉER DANS L’APP', control: 'CONTRÔLER SUR UNO', refine: 'AFFINER LE PROFIL',
    surface: 'INGÉNIERIE DE SURFACE PRÉCISE', finishes: 'L’OR POUR LA PURETÉ.\nLE NITRURE DE TITANE POUR LA CHALEUR.', finishesBody: 'HeatCore est proposé avec deux finitions PVD conçues avec précision. L’or 24K sur toute la surface confère à l’édition Gold une expression nette et précise du goût et un caractère particulièrement noble. Le nitrure de titane apporte à l’édition PRO une stabilité à haute température pour un usage fréquent et prolongé.', heatingCurve: 'COURBE DE CHAUFFE', grill: 'GRIL',
  },
  es: { upperShort: 'SUPERIOR', lowerShort: 'INFERIOR',
    three: 'TRES CALENTADORES.\nUN EQUILIBRIO CONTINUO.', upper: 'CALOR SUPERIOR', grillMode: 'MODO PARRILLA', lower: 'CALOR INFERIOR', upperBody: 'Mantiene la temperatura principal de la sesión.', grillBody: 'Añade intensidad dirigida justo cuando hace falta.', lowerBody: 'Precalienta gradualmente la mezcla desde abajo.', architecture: 'Arquitectura de calentamiento preciso', heatersBody: 'Tres calentadores controlados de forma independiente crean y mantienen el perfil elegido, dirigiendo el calor exactamente donde se necesita.',
    sails: 'ALETAS DE AIRE ACTIVAS', release: 'CALOR EXCESIVO.\nLIBERADO CONTINUAMENTE.', sailsBody: 'Dos aletas de aire de aluminio alejan el exceso de calor de la cámara de la cápsula y del calentador inferior. La liberación pasiva continua mantiene la mezcla estable, predecible y protegida del sobrecalentamiento durante toda la sesión.',
    profiles: 'PERFILES DE CALOR PROGRAMABLES', power: 'POTENCIA, MOLDEADA EN EL TIEMPO.', profilesBody: 'HeatCore utiliza algoritmos lineales y por intervalos para controlar los cambios de potencia durante la sesión. Crea y perfecciona el perfil de calor en la aplicación RAMSIDER y gestiona después la sesión activa desde la pantalla táctil de UNO.', create: 'CREAR EN LA APP', control: 'CONTROLAR EN UNO', refine: 'PERFECCIONAR EL PERFIL',
    surface: 'INGENIERÍA DE SUPERFICIE PRECISA', finishes: 'ORO PARA LA PUREZA.\nNITRURO DE TITANIO PARA EL CALOR.', finishesBody: 'HeatCore se ofrece en dos acabados PVD de ingeniería. El oro de 24K en toda la superficie aporta a la edición Gold una expresión limpia y precisa del gusto y un carácter especialmente noble. El nitruro de titanio dota a la edición PRO de estabilidad a alta temperatura con un uso frecuente y prolongado.', heatingCurve: 'CURVA DE CALOR', grill: 'PARRILLA',
  },
  it: { upperShort: 'SUPERIORE', lowerShort: 'INFERIORE',
    three: 'TRE RISCALDATORI.\nUN EQUILIBRIO CONTINUO.', upper: 'CALORE SUPERIORE', grillMode: 'MODALITÀ GRILL', lower: 'CALORE INFERIORE', upperBody: 'Mantiene la temperatura principale della sessione.', grillBody: 'Aggiunge intensità mirata esattamente quando serve.', lowerBody: 'Preriscalda gradualmente la miscela dal basso.', architecture: 'Architettura di riscaldamento precisa', heatersBody: 'Tre riscaldatori controllati indipendentemente definiscono e mantengono il profilo scelto, dirigendo il calore esattamente dove serve.',
    sails: 'ALETTE D’ARIA ATTIVE', release: 'CALORE IN ECCESSO.\nRILASCIATO CONTINUAMENTE.', sailsBody: 'Due alette d’aria in alluminio allontanano il calore in eccesso dalla camera della capsula e dal riscaldatore inferiore. Il rilascio passivo continuo mantiene la miscela stabile, prevedibile e protetta dal surriscaldamento per tutta la sessione.',
    profiles: 'PROFILI DI CALORE PROGRAMMABILI', power: 'POTENZA, MODELLATA NEL TEMPO.', profilesBody: 'HeatCore utilizza algoritmi lineari e a intervalli per controllare le variazioni di potenza durante la sessione. Crea e affina il profilo di calore nell’app RAMSIDER, poi gestisci la sessione attiva direttamente dal display touch di UNO.', create: 'CREA NELL’APP', control: 'CONTROLLA SU UNO', refine: 'AFFINA IL PROFILO',
    surface: 'INGEGNERIA DI SUPERFICIE PRECISA', finishes: 'ORO PER LA PUREZZA.\nNITRURO DI TITANIO PER IL CALORE.', finishesBody: 'HeatCore è disponibile con due finiture PVD progettate con precisione. L’oro 24K sull’intera superficie conferisce all’edizione Gold un’espressione pulita e precisa del gusto e un carattere particolarmente nobile. Il nitruro di titanio dona all’edizione PRO stabilità ad alte temperature nell’uso frequente e prolungato.', heatingCurve: 'CURVA DI CALORE', grill: 'GRILL',
  },
  tr: { upperShort: 'ÜST', lowerShort: 'ALT',
    three: 'ÜÇ ISITICI.\nKESİNTİSİZ BİR DENGE.', upper: 'ÜST ISI', grillMode: 'IZGARA MODU', lower: 'ALT ISI', upperBody: 'Seansın temel sıcaklığını korur.', grillBody: 'Gerektiğinde yoğunluğu tam olarak artırır.', lowerBody: 'Karışımı alttan kademeli olarak ön ısıtır.', architecture: 'Hassas ısıtma mimarisi', heatersBody: 'Bağımsız kontrol edilen üç ısıtıcı seçilen profili oluşturur ve korur; ısıyı tam olarak gereken yere yönlendirir.',
    sails: 'AKTİF HAVA KANATLARI', release: 'FAZLA ISI.\nKESİNTİSİZ TAHLİYE.', sailsBody: 'İki alüminyum hava kanadı fazla ısıyı kapsül haznesinden ve alt ısıtıcıdan uzaklaştırır. Kesintisiz pasif tahliye, seans boyunca karışımı dengeli, öngörülebilir ve aşırı ısınmaya karşı korunaklı tutar.',
    profiles: 'PROGRAMLANABİLİR ISI PROFİLLERİ', power: 'ZAMAN İÇİNDE ŞEKİLLENEN GÜÇ.', profilesBody: 'HeatCore, seans boyunca gücün değişimini kontrol etmek için doğrusal ve aralıklı algoritmalar kullanır. RAMSIDER uygulamasında ısı profilini oluşturup geliştirin, ardından aktif seansı doğrudan UNO’nun dokunmatik ekranından yönetin.', create: 'UYGULAMADA OLUŞTUR', control: 'UNO ÜZERİNDEN KONTROL', refine: 'PROFİLİ GELİŞTİR',
    surface: 'HASSAS YÜZEY MÜHENDİSLİĞİ', finishes: 'SAFLIK İÇİN ALTIN.\nISI İÇİN TİTANYUM NİTRÜR.', finishesBody: 'HeatCore iki özel PVD yüzey kaplamasıyla sunulur. Tüm yüzeyi kaplayan 24K altın, Gold sürümüne temiz ve hassas bir zevk ifadesi ve belirgin biçimde asil bir karakter kazandırır. Titanyum nitrür, PRO sürümüne sık ve uzun süreli kullanımda yüksek sıcaklık kararlılığı sağlar.', heatingCurve: 'ISITMA EĞRİSİ', grill: 'IZGARA',
  },
  ar: { upperShort: 'علوي', lowerShort: 'سفلي',
    three: 'ثلاثة سخانات.\nتوازن مستمر.', upper: 'الحرارة العلوية', grillMode: 'وضع الشواء', lower: 'الحرارة السفلية', upperBody: 'يحافظ على درجة الحرارة الأساسية للجلسة.', grillBody: 'يضيف شدة مركزة بدقة عند الحاجة.', lowerBody: 'يسخن المزيج تدريجياً من الأسفل.', architecture: 'بنية تسخين دقيقة', heatersBody: 'تشكل ثلاثة سخانات مستقلة التحكم الملف المختار وتحافظ عليه، وتوجه الحرارة بدقة إلى المكان المطلوب.',
    sails: 'زعانف هوائية نشطة', release: 'الحرارة الزائدة.\nتصريف مستمر.', sailsBody: 'تسحب زعنفتان هوائيتان من الألمنيوم الحرارة الزائدة بعيداً عن حجرة الكبسولة والسخان السفلي. يحافظ التصريف السلبي المستمر على استقرار المزيج وقابليته للتوقع ويحميه من فرط التسخين طوال الجلسة.',
    profiles: 'ملفات حرارة قابلة للبرمجة', power: 'قدرة تتشكل بمرور الوقت.', profilesBody: 'يستخدم HeatCore خوارزميات خطية ومتقطعة للتحكم في تغير القدرة طوال الجلسة. أنشئ ملف الحرارة وحسنه في تطبيق RAMSIDER، ثم أدر الجلسة النشطة مباشرة من شاشة UNO اللمسية.', create: 'أنشئ في التطبيق', control: 'تحكم على UNO', refine: 'حسن الملف',
    surface: 'هندسة سطحية دقيقة', finishes: 'الذهب للنقاء.\nنيتريد التيتانيوم للحرارة.', finishesBody: 'يتوفر HeatCore بتشطيبين هندسيين بتقنية PVD. يمنح الذهب عيار 24 قيراطاً على كامل السطح إصدار Gold تعبيراً صافياً ودقيقاً عن الذوق وطابعاً نبيلاً مميزاً. يمنح نيتريد التيتانيوم إصدار PRO ثباتاً عند درجات الحرارة المرتفعة مع الاستخدام المتكرر والمستمر.', heatingCurve: 'منحنى التسخين', grill: 'الشواء',
  },
  zh: { upperShort: '上部', lowerShort: '下部',
    three: '三个加热器。\n持续保持平衡。', upper: '上部加热', grillMode: '烧烤模式', lower: '下部加热', upperBody: '维持主要的使用温度。', grillBody: '在需要时精准增加集中强度。', lowerBody: '从下方逐渐预热混合物。', architecture: '精准加热架构', heatersBody: '三个独立控制的加热器塑造并维持所选曲线，将热量精准引导至需要的位置。',
    sails: '主动导流翼', release: '多余热量。\n持续释放。', sailsBody: '双铝制导流翼将多余热量从胶囊腔和下部加热器带走。持续的被动散热让混合物在整个使用过程中保持稳定、可预测，并免受过热影响。',
    profiles: '可编程加热曲线', power: '随时间塑造功率。', profilesBody: 'HeatCore 使用线性和间隔算法控制使用过程中功率的变化。在 RAMSIDER 应用中创建并优化加热曲线，然后直接通过 UNO 触摸屏管理当前过程。', create: '在应用中创建', control: '在 UNO 上控制', refine: '优化曲线',
    surface: '精准表面工程', finishes: '黄金带来纯净。\n氮化钛应对高温。', finishesBody: 'HeatCore 提供两种经过工程设计的 PVD 表面处理。全表面 24K 黄金赋予 Gold 版本清晰精准的品味表达与鲜明高贵的气质。氮化钛为 PRO 版本在频繁、持续使用中提供高温稳定性。', heatingCurve: '加热曲线', grill: '烧烤',
  },
  ja: { upperShort: '上部', lowerShort: '下部',
    three: '3つのヒーター。\n途切れないバランス。', upper: '上部加熱', grillMode: 'グリルモード', lower: '下部加熱', upperBody: 'セッションの基本温度を維持します。', grillBody: '必要なときに狙った強度を正確に加えます。', lowerBody: 'ブレンドを下から徐々に予熱します。', architecture: '精密な加熱構造', heatersBody: '独立制御された3つのヒーターが選択したプロファイルを形成・維持し、必要な場所へ正確に熱を届けます。',
    sails: 'アクティブエアセイル', release: '余分な熱。\n継続的に放出。', sailsBody: '2枚のアルミ製エアセイルがカプセル室と下部ヒーターから余分な熱を逃がします。連続した受動放熱により、セッション全体を通じてブレンドを安定した予測可能な状態に保ち、過熱から守ります。',
    profiles: 'プログラム可能な加熱プロファイル', power: '時間に沿って形づくられる出力。', profilesBody: 'HeatCore は線形・間隔アルゴリズムでセッション中の出力変化を制御します。RAMSIDER アプリで加熱プロファイルを作成・調整し、UNO のタッチ画面から進行中のセッションを直接管理できます。', create: 'アプリで作成', control: 'UNO で操作', refine: 'プロファイルを調整',
    surface: '精密な表面技術', finishes: '純粋さのためのゴールド。\n熱のための窒化チタン。', finishesBody: 'HeatCore には2種類の設計された PVD 仕上げがあります。全面の24Kゴールドが Gold エディションにすっきりと精緻な趣味の表現と気品を与えます。窒化チタンは、頻繁で長時間の使用でも PRO エディションに高温安定性をもたらします。', heatingCurve: '加熱曲線', grill: 'グリル',
  },
  ko: { upperShort: '상부', lowerShort: '하부',
    three: '세 개의 히터.\n지속적인 균형.', upper: '상부 가열', grillMode: '그릴 모드', lower: '하부 가열', upperBody: '세션의 기본 온도를 유지합니다.', grillBody: '필요할 때 집중된 강도를 정밀하게 더합니다.', lowerBody: '블렌드를 아래에서 서서히 예열합니다.', architecture: '정밀 가열 구조', heatersBody: '독립적으로 제어되는 세 개의 히터가 선택한 프로필을 만들고 유지하며, 필요한 곳에 열을 정확하게 전달합니다.',
    sails: '액티브 에어 세일', release: '과도한 열.\n지속적으로 방출.', sailsBody: '두 개의 알루미늄 에어 세일이 캡슐 챔버와 하부 히터에서 과도한 열을 빼냅니다. 지속적인 수동 방출은 세션 내내 블렌드를 안정적이고 예측 가능한 상태로 유지하며 과열로부터 보호합니다.',
    profiles: '프로그래밍 가능한 열 프로필', power: '시간에 따라 형성되는 출력.', profilesBody: 'HeatCore는 선형 및 구간 알고리즘으로 세션 중 출력 변화를 제어합니다. RAMSIDER 앱에서 열 프로필을 만들고 다듬은 뒤 UNO 터치 디스플레이에서 진행 중인 세션을 직접 관리하세요.', create: '앱에서 생성', control: 'UNO에서 제어', refine: '프로필 조정',
    surface: '정밀 표면 엔지니어링', finishes: '순수함을 위한 금.\n열을 위한 질화 티타늄.', finishesBody: 'HeatCore는 두 가지 설계된 PVD 마감으로 제공됩니다. 표면 전체를 덮는 24K 금은 Gold 에디션에 깔끔하고 정밀한 취향의 표현과 고귀한 성격을 더합니다. 질화 티타늄은 빈번하고 지속적인 사용에도 PRO 에디션에 고온 안정성을 제공합니다.', heatingCurve: '가열 곡선', grill: '그릴',
  },
};
